### ISSUE TITLE
엔진은 브레이크를 밟은 상태에서 켜지도록 구현

### ISSUE THREAD

**Issue by Byuntil** [jbnu-se-project/car#1]
# Description
브레이크와 엔진버튼이 동시에 입력이 되어야 엔진이 켜지는 기능
하지만 브레이크 다음 엔진버튼으로 전 후 관계는 가지고 있다.

예시 시나리오 :
1. 엔진 버튼만 누른 경우 - 시동 실패
2. 브레이크와 엔진 버튼을 순차적으로 누른 경우 - 시동 실패
3. 브레이크와 엔진 버튼을 동시에 누른 경우 - 시동 성공

# Todo
1. 테스트 코드 작성
   - [x] 엔진 시동 조건에 대한 단위 테스트 구현
   - [x] 예외 케이스 테스트 구현

2. 기능 구현
   - [x] 동시 입력 분리 메커니즘 구현
   - [x] EngineController 로직 수정
   - [x] CarCommandExecutor 연동

# Etc
