### ISSUE TITLE
예외상황 처리하기

### ISSUE THREAD

**Issue by zzl-hyun** [jbnu-se-project/car#4]
# Description
엔진이 켜지면 안되는 케이스 처리

예시 시나리오 :

1. 브레이크와 엔진 버튼을 동시에 누른 경우 - 시동 성공
2. 엑셀, 브레이크 그리고 엔진 버튼을 동시에 누른 경우 - 시동 실패

# Todo
테스트 케이스 설계
- [x] 테스트 케이스 코드 작성
- [x] 테스트 케이스에 대한 유닛테스트 진행

코드 수정
- [x] engine_controller.py 수정

# Etc
